---
title: '2015-05-22'
author: "林茂廷"
date: "5/22/2019"
output: html_document
---

## midterm 6.2

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```

```{r}
(invoiceList$`訂單時區`=="America/New_York") -> nyLogical
(invoiceList$`訂單時區`=="Asia/Taipei") -> tpLogical

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

library(lubridate)
ymd_hms(invoiceList$`訂單時區之下單時間`[nyLogical],
          tz="America/New_York") -> nyDateTime

invoiceList$`UTC時間`[nyLogical] <-
  with_tz(nyDateTime,tzone="UTC")

ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei") -> tpDateTime
invoiceList$`UTC時間`[tpLogical] <-
  with_tz(tpDateTime,tzone="UTC")

invoiceList 


```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"

(invoiceList$`訂單時區`=="America/New_York") -> nyLogical
(invoiceList$`訂單時區`=="Asia/Taipei") -> tpLogical

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

library(lubridate)
ymd_hms((invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei") -> tpDateTime
        
```

##請把以America/New_York時區輸入的時間字串"1973-02-21 12:05:22"，轉成date time class, 再改成Asia/Taipei時間顯示。
```{r}
library(lubridate)
ymd_hms("1973-02-21 12:05:22",tz="America/New_York")-> datetime1
with_tz(datetime1,tzone = "Asia/Taipei")-> datetime2
datetime2

ymd_hms_tzChange <- function(input,datetime1,datetime2){
  time1 <- ymd_hms(input,tz=datetime1)
  answer <- with_tz(time1,tzone = datetime2)
  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```

```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
```

```{r}
library(stringr);library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
```

##請寫一個函數名稱為date_convert_twYM，且date_convert_twYM(x)可以把一個民國年月字串物件x轉成date time class的西元年月日物件輸出。
```{r}
date_convert_twYM<-function(x){
 yyyy<-as.integer(str_extract(x,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(x,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
return(yyyymmdd)
}
```
##老師版
```{r}
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
yyyymmdd

```

```{r}
date_convert_twYM <- function(twDates){
  #twDates
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
}
```

##老師正解
沒有預設值
```{r}
date_convert_twYM <- function(twDates){
  #twDates
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
}
```
有預設值
```{r}
date_convert_twYM <- function(twDates,dd="01"){
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-"))
  yyyymmdd
}
```

