---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c('小明說：'明天不用上課。'',
               '小花說：'真的嗎？'')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c('助教說："明天要上實習課。"',
               '我說："可以不要嗎？"')

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
sum(aLogical)
```

```{r}
birthplace<-factor(
  c("台中市","台北市","新北市")
)
class(birthplace)
typeof(birthplace)
levels(birthplace)
as.integer(birthplace)
```

```{r}
horoscope<-factor(c("天秤座","牡羊座","處女座"))
levels(horoscope)
```

```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject
```

```{r}
typeof(dtObject)
```

```{r}
as.double(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-04-01 04:01:00", tz="Asia/Taipei")
USDateTime <- with_tz(twDateTime,tzone = "America/New_York")
USDateTime
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
SeoulDateTime <- with_tz(twDateTime,tzone="Asia/Seoul")
SeoulDateTime
```

```{r}
nowtwDateTime <- ymd_hms("2019-03-27 15:32:00", tz="Asia/Taipei")
nowtwDateTime
nowTokyoDateTime <- with_tz(nowtwDateTime,tzone="Asia/Tokyo")
nowTokyoDateTime
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```

```{r}
typeof(twDateTime)
as.double(twDateTime)
as.double(LisbonDateTime)
as.double(SeoulDateTime)
```

```{r}
object
```


```{r}
twDateTime <- mdy_hms("3/14/2019 8:18:47", tz="Asia/Taipei")
twDateTime
```

```{r}
twDateTime <- ymd ("2018-09-11", tz="Asia/Taipei")
twDateTime
```

```{r}
twDateTime <- mdy("March 3, 2019", tz="Asia/Taipei")
twDateTime
```

```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))   
as.integer(ymd("2019-03-11"))
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
a+bL
aL+bL
class(aL)
class(bL)
```

```{r}
twDateTime <- ymd_hms("2019-03-27 15:32:00", tz="Asia/Taipei")
twDateTime
twDateTime+100
```

```{r}
DateTime1 <- ymd("2019-08-11")
DateTime2 <- ymd("2000-02-01")
DateTime1-DateTime2
```

```{r}
startingDate <- ymd("1997-09-23")
```

```{r}
startingDate + years(20)
```

```{r}
startingDate + dyears(20)
```

#Relational Operators
```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x<=y
x>=y
x==y
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3==y3
```
```{r}
x3!=y3
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

